### PR TITLE
Add Django and Flask courses

### PR DESCRIPTION
**Pull request by TareqMonwer**

### CODE REVIEW

**Comment by kingRayhan** [comment]
@TareqMonwer Thanks for your contribution :heart_eyes:

**Comment by TareqMonwer** [comment]
> @TareqMonwer Thanks for your contribution heart_eyes

My pleasure :)

**Comment by kingRayhan** [comment]
Expecting more contribution from you :+1:

**Comment by TareqMonwer** [comment]
Sure thing, I'll be happy doing so 😃

**Pull request merged**
